sonar.organization=dolmen-go
sonar.projectKey=dolmen-go_goeval

sonar.go.activate=true
sonar.dre.go.activate=true

# https://docs.sonarsource.com/sonarqube-server/analyzing-source-code/test-coverage/go-test-coverage
# Output of "go test -coverprofile" => see GH workflow
# sonar.go.coverage.reportPaths=

# Ignore coverage report for _test.go because "go test" doesn't report them anyway
sonar.coverage.exclusions=**/*_test.go, cover.sh

# Output of "go test -json" => see GH workflow
# sonar.go.tests.reportPaths=

# TODO
# sonar.go.golangci-lint.reportPaths=

# TODO
# sonar.githubactions.actionlint.reportPaths

# https://sonarcloud.io/project/settings?category=exclusions&id=dolmen-go_goeval

# Ignore duplications in unit test code
# Ignore duplucations in play.go and share.go: this is a design choice
sonar.cpd.exclusions=**/*_test.go, sub/play/play.go, sub/share/share.go