name: Go
on: [push]
jobs:

  build:
    name: Build&test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - stable
        - oldstable
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Build
      run: go build -v .

    - name: Test
      run: ./goeval 'fmt.Println("Hello, world")'

    - name: Check version
      run: ./goeval 'fmt.Println(runtime.Version())'

    - name: Run tests
      run: go test -v ./...

    - name: Test -play
      run: |
        out="$(./goeval -play 'fmt.Println(time.Now())')"
        expected='2009-11-10 23:00:00 +0000 UTC m=+0.000000001'
        if [ "$out" != "$expected" ]; then
          echo "got:      $out"
          echo "expected: $expected"
          exit 1
        fi