name: Go
on: [push]
jobs:

  build:
    name: Build&test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - stable
        - oldstable
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Build
      run: go build -v .

    - name: Test
      run: ./goeval 'fmt.Println("Hello, world")'

    - name: Check version
      run: ./goeval 'fmt.Println(runtime.Version())'

    - name: Run tests
      run: go test -v ./...
