# See:
# - https://yossarian.net/til/post/any-program-can-be-a-github-actions-shell/
# - https://news.ycombinator.com/item?id=43617493

name: goeval as GitHub action
on: [push]
jobs:

  build:
    name: goeval as GitHub action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - stable
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Install goeval in $GOBIN
      run: go install . # or github.com/dolmen-go/goeval@v1

    - shell: echo {0}
      run: ignore

    - name: goeval called as a GitHub action shell
      # {0} is the filename that point to the 'run' content.
      # As goeval doesn't accept (yet!) direct filename input, we must
      # use a shell that send the GitHub-generated file to goeval's stdin.
      shell: goeval - < {0}
      # run: fmt.Println("goeval called as a GitHub action")
      run: fmt.Println(os.Args)

    #- name: goeval2
    #  shell: goeval fmt.Println("OK");fmt.Println("{0}")
    #  run: ignore

    - name: Print buildinfo
      shell: env CGO_ENABLED=0 goeval - <"{0}"
      run: |
        bi, _ := debug.ReadBuildInfo()
        fmt.Print(bi)
